workflows:
  version: 2
  node-multi-build:
    jobs:
      - test:
version: 2
jobs:
    test:
        docker:
            - image: node:latest
        steps:
            - checkout
            - restore_cache:
                  keys:
                      - v{{ .Environment.CIRCLE_CACHE_VERSION }}-yarn-lock-{{ .Branch }}-{{ .Environment.CIRCLE_JOB }}-{{ checksum "yarn.lock" }}
                      - v{{ .Environment.CIRCLE_CACHE_VERSION }}-yarn-lock-master-{{ .Environment.CIRCLE_JOB }}-{{ checksum "yarn.lock" }}
                      - v{{ .Environment.CIRCLE_CACHE_VERSION }}-yarn-cache-{{ .Branch }}-{{ .Environment.CIRCLE_JOB }}
                      - v{{ .Environment.CIRCLE_CACHE_VERSION }}-yarn-cache-master-{{ .Environment.CIRCLE_JOB }}
            - run:
                  name: Install dependencies
                  command: yarn install
            - run:
                  name: Build
                  command: yarn build
            - save_cache:
                  key: v{{ .Environment.CIRCLE_CACHE_VERSION }}-yarn-lock-{{ .Branch }}-{{ .Environment.CIRCLE_JOB }}-{{ checksum "yarn.lock" }}
                  paths:
                      - node_modules
            - save_cache:
                  key: v{{ .Environment.CIRCLE_CACHE_VERSION }}-yarn-lock-{{ .Branch }}-{{ .Environment.CIRCLE_JOB }}-{{ checksum "yarn.lock" }}
                  paths:
                      - ~/.cache/yarn
    test:
        <<: *node-base
        docker:
            - image: node:11
